### ISSUE TITLE
兄弟你从web端下载文件的时候，是服务端先解压再传过来吗

### ISSUE THREAD

**Issue by 1900100209** [dodamce/cloud-backups#1]

**Comment by backup-nuc** [comment]
没错，浏览器点击下载后，如果这个文件长时间没有被下载，那么服务器就是先解压然后下载，这个时间设置可以看配置文件上面



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hhx ***@***.***&gt;
发送时间: 2024年4月23日 21:00
收件人: dodamce/cloud-backups ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [dodamce/cloud-backups] 兄弟你从web端下载文件的时候，是服务端先解压再传过来吗 (Issue #1)

**Comment by 1900100209** [comment]
看了下现在的逻辑（server.cpp的download函数），是先判断数据是否被压缩，压缩的话，先解压，再传给客户端。

server.cpp的RunModule那里server.Get，这个get_handlers_方法后面就没有了，httplib.h这个是哪个第三方库呀
```c++
inline Server &Server::Get(const std::string &pattern, Handler handler) {
  get_handlers_.emplace_back(make_matcher(pattern), std::move(handler));
  return *this;
}
```

**Comment by backup-nuc** [comment]
httplib.h这个是cpp-httplib 这个库，直接在Github 上搜索就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hhx ***@***.***&gt;
发送时间: 2024年4月23日 21:58
收件人: dodamce/cloud-backups ***@***.***&gt;
抄送: dodamce ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [dodamce/cloud-backups] 兄弟你从web端下载文件的时候，是服务端先解压再传过来吗 (Issue #1)





 
看了下现在的逻辑（server.cpp的download函数），是先判断数据是否被压缩，压缩的话，先解压，再传给客户端。
 
server.cpp的RunModule那里server.Get，这个get_handlers_方法后面就没有了，httplib.h这个是哪个第三方库呀
 inline Server &amp;Server::Get(const std::string &amp;pattern, Handler handler) {   get_handlers_.emplace_back(make_matcher(pattern), std::move(handler));   return *this; }

**Comment by backup-nuc** [comment]
https://github.com/yhirose/cpp-httplib

**Comment by backup-nuc** [comment]
具体是这样的我项目里的sever.hpp里面封装了一个httplib第三方库的一个服务器，这个sever.Get可以理解为把HTTP请求的uri和这个uri需要处理的函数进行绑定。具体可以看我给你发的那个链接，里面非常详细的使用案例。

**Comment by backup-nuc** [comment]
完整的项目链接看gitee把，我是gitee同步到github上的，客户端代码因为大小关系没有同步上https://gitee.com/dodamce/cloud-backups

**Comment by 1900100209** [comment]
好的，谢谢，方便加个联系方式吗? :smiley:
我是桂林电子科技大学的

**Comment by backup-nuc** [comment]
我的qq 3030949391 ENIAC
